global:
  checkNewVersion: true
  sendAnonymousUsage: false

# Configure Docker as the provider
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false # Explicitly enable services for Traefik
  file:
    filename: /etc/traefik/rules.yml # Path to dynamic rules file

# Define API and dashboard (secured)
api:
  dashboard: true
  insecure: true # DO NOT expose this directly. We will secure it with labels in docker-compose.

# Define entrypoints (ports Traefik listens on)
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"
  websecure:
    address: ":443"

# Configure Let's Encrypt SSL certificate generation
certificatesResolvers:
  cloudflare:
    acme:
      email: ${CLOUDFLARE_EMAIL}
      storage: "/etc/traefik/acme.json"
      dnsChallenge:
        provider: "cloudflare"
        # The following environment variables are passed from docker-compose.yml
        # CLOUDFLARE_DNS_API_TOKEN
        # CLOUDFLARE_ZONE_API_TOKEN (not used if using DNS token)