name: Test and Deploy Traefik Stack

on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]

jobs:
  test-configuration:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker
      uses: docker/setup-buildx-action@v3
    
    - name: Validate docker-compose files
      run: |
        docker-compose config -q
        echo "docker-compose.yml validation passed"
        
        # Validate service compose files
        for svc in services/*/docker-compose.yml; do
          if [ -f "$svc" ]; then
            echo "Validating $svc"
            docker-compose -f "$svc" config -q
            echo "$svc validation passed"
          fi
        done
    
    - name: Check configuration files
      run: |
        required_files=(
          "traefik/traefik.yml"
          "traefik/config/middlewares.yml"
          "traefik/config/tls.yml"
          ".env.example"
        )
        
        for file in "${required_files[@]}"; do
          if [ ! -f "$file" ]; then
            echo "Missing required file: $file"
            exit 1
          fi
          echo "Found: $file"
        done
        
        touch traefik/acme.json
        chmod 600 traefik/acme.json
        perms=$(stat -c %a traefik/acme.json)
        if [ "$perms" != "600" ]; then
          echo "acme.json should have 600 permissions, got $perms"
          exit 1
        fi
        echo "acme.json permissions are correct (600)"

  security-scan:
    runs-on: ubuntu-latest
    needs: test-configuration
    steps:
    - uses: actions/checkout@v4
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'config'
        hide-progress: false
        format: 'sarif'
        output: 'trivy-results.sarif'
        exit-code: '1'
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'
    
    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

  integration-test:
    runs-on: ubuntu-latest
    needs: [test-configuration, security-scan]
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker
      uses: docker/setup-buildx-action@v3
    
    - name: Copy .env.example to .env for testing
      run: cp .env.example .env
    
    - name: Start Traefik stack
      run: |
        mkdir -p traefik/{logs,config}
        touch traefik/acme.json
        chmod 600 traefik/acme.json
        echo "Starting minimal Traefik container for testing..."
        docker-compose up -d traefik
    
    - name: Wait for Traefik to start
      run: |
        echo "Waiting for Traefik to become healthy..."
        timeout 60 bash -c 'until docker inspect traefik | grep -q "healthy"; do sleep 2; done'
    
    - name: Test Traefik health check
      run: |
        echo "Testing Traefik API..."
        docker exec traefik traefik healthcheck --ping
        echo "Traefik health check passed"
    
    - name: Test configuration validation script
      run: |
        chmod +x scripts/validate-config.sh
        ./scripts/validate-config.sh
    
    - name: Cleanup
      if: always()
      run: docker-compose down -v
